### ISSUE TITLE
DataObject::Type::AbstractGeometry will never be used

### ISSUE THREAD

**Issue by JDuffeyBQ** [BlueQuartzSoftware/complex#112]
The derived classes of `AbstractGeometry` (and `AbstractGeometry2D`/`AbstractGeometry3D`) will have `getDataObjectType()` overridden by derived classes so that their associated `DataObject::Type` enum value will never be used.

**Comment by imikejackson** [comment]
Implemented in the refactored Geometry Codes. Closing
