### ISSUE TITLE
Add more checks to the LinkGeometryDataFilter to ensure that the selected arrays have the correct number of tuples

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#116]

**Comment by craigusr** [comment]
1. Create a Pipeline with DataArrays an ImageGemoetry and a LinkGeometryDataFilter
2. Make sure that the tuple sizes in the Create Data Arrays and the LInkGeometryDataFilter don't match
3. If you go to the Visual properties after dragging the image geometry the Array dropdown is empty

We would like the Filter to issue a warning

**Comment by imikejackson** [comment]
This functionality has been superseded by the AttributeMatrix implementation
