### ISSUE TITLE
Crop Image Geometry axis options are broke for "Use Physical Units"

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#1160]
Only clicking on "Crop X Dimension" and it crops in the Y dimension.

![Screenshot 2024-12-07 at 10 35 41](https://github.com/user-attachments/assets/7d357ac5-dde1-4aea-9ec5-9bbdeaac3b5c)

**Comment by joeykleingers** [comment]
Closing this issue since I can't seem to reproduce the bug.
