### ISSUE TITLE
FILTER: Need to implement a PLY reader for both Binary and ASCII PLY Files

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#1161]
LiDAR uses these kinds of files. KITTO-360 has ton example files.

https://github.com/vilya/miniply

miniply is also in vcpkg. It is header only.

https://github.com/vilya/ply-parsing-perf?tab=readme-ov-file page has a good summary of the various PLY parsers out there. 

## Python Reader Available

The available "MeshIO" reader that is in the NXDataAnalysisToolkit python plugin will read .ply files as long as there are "Cells" in the .ply file. If there are only point clouds, then the reader will fail preflight:

@joeykleingers Update the MeshIO Python filter to allow the reading of Point Cloud data. The Example data file has been slacked to you.

**Comment by joeykleingers** [comment]
Finished via PR #1163.
