### ISSUE TITLE
InterpolatePointCloudToRegularGrid and Test

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#125]
- [ ] This filter is missing a few parameters from the original (Copied Array Suffix and Interpolated array suffix).

- [x] It is missing a check for boolean in the interpolated arrays (not sure how to interpolate booleans).

- [x] The test has boolean arrays to interpolate leading to nullpointers.

- [ ] the filter does not take into consideration the interploated suffix that the user should be filling in (or have a default value assigned).

**Comment by nyoungbq** [comment]
Issues 2/4 and 3/4 were not an issue as the accepted arrays to interpolate are only allowing numeric types : ie boolean is not an issue

**Comment by nyoungbq** [comment]
Another found issue is that test 1 was never actually being run this is fixed now

**Comment by imikejackson** [comment]
The remaining issues have been implemented. Closing
