### ISSUE TITLE
Crop Image Geometry does not crop correctly

### ISSUE THREAD

**Issue by nyoungbq** [BlueQuartzSoftware/complex#354]
During test case runs I stumbled into a rabbit hole that showed out that Crop Image Geometry doesn't output data correctly. The test case for the file doesn't test rigorously enough, so it wasn't caught until today when the SmallIN100 was dropped into HDF5 view during a fix for ErodeDilateDataTest case. Upon further dive the the Crop Image Geometry filter itself seems to have an incorrect step. 

Steps to replicate:
1) Run CTest to get the CropImageGeometryTest to print a dream3d file containing the data
2) Drop dream3d file from CropImageGeometryTest into H5Web on VS Code

**Comment by imikejackson** [comment]
PR #355 Will fix this issue.
