### ISSUE TITLE
Porting Filters from Core to ComplexCore

### ISSUE THREAD

**Issue by nyoungbq** [BlueQuartzSoftware/complex#389]
# Filters to port over from `complex_plugins/Core` into `ComplexCore` #

## These filters have an Orientation Analysis Plugin dependency ##

In order to remedy this issue of cross dependency, one must rework the `.dream3d` input test file to accommodate the Orientation Analysis filters that are run to prep the test file for running the filter or analyzing the results. Here is the list of filters with said dependency:

- [x] AlignSectionsFeatureCentroidFilter
- [x] ErodeDilateBadDataFilter
- [x] FindNeighborhoodsFilter

## Needs Further Filter Review ##

This has abnormalities that need to be patched before they can be ported.

- [x] RotateSampleRefFrameFilter - (Has missing actions in preflight) 

## Needs Further Test Case Review ##

- [x] FillBadDataFilter - (Needs test case implemented)
- [x] RemoveFlaggedFeaturesFilter - (Test the Neighborlist warning logic from preflight)
- [x] ResampleImageGeomFilter - (Extensive preflight, explore a Test Invalid Execution test case)

## Need an Overarching Test Case for Instantiation ##

There needs a test case to instantiate all filters that are compiled - must be done dynamically

Also after dynamic test case completion, one must go through and strip out the **instantiation test case** from each test file.

## If filter is not on this list but is in Core it is in the process of being ported already ##

**Comment by imikejackson** [comment]
## ResampleImageGeomFilter and CropImageGeomFilter
These could in theory use a unit test where there is both String data and NeighborList at the Cell level. Neither filter will handle these cases by they do provide warnings to the user.
The preflight of both has been updated (on another PR) to explain a bit more what is going on in the preflight.

Unit Tests are implemented covering more variations on the input parameters and ResampleImageGeomFilter is moved to the ComplexCore Plugin

CropImageGeomFilter had its unit test also updated.

https://github.com/BlueQuartzSoftware/complex/pull/399

**Comment by nyoungbq** [comment]
Dynamic Test Instantiation Test Case Merged
https://github.com/BlueQuartzSoftware/complex/pull/406

MERGED

**Comment by imikejackson** [comment]
AlignSectionsFeatureCentroidFilter has been updated, fixed and moved to ComplexCore. 

https://github.com/BlueQuartzSoftware/complex/pull/426
https://github.com/BlueQuartzSoftware/complex_plugins/pull/90

MERGED

**Comment by imikejackson** [comment]
FillBadDataFilter 

Completed in https://github.com/BlueQuartzSoftware/complex/pull/405

MERGED

**Comment by imikejackson** [comment]
## ErodeDilateBadData Filter

https://github.com/BlueQuartzSoftware/complex/pull/439

MERGED

**Comment by nyoungbq** [comment]
## Remove Flagged Features

https://github.com/BlueQuartzSoftware/complex/pull/474

MERGED

**Comment by nyoungbq** [comment]
## Find Neighborhoods

https://github.com/BlueQuartzSoftware/complex/pull/479

MERGED
