### ISSUE TITLE
ITK Filter Parameters need to be organized

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#537]
The following filters should have their parameters organized better. See original SIMPL/DREAM3D for better layouts.

* ITK Mask Image Filter
* ITK Gradient Magnitude Image Filter

In fact, can we figure out the "standard" code so we just have the user send in the actual data array and then the code can back figure out the ImageGeometry? The input image data would have to be in a Cell Level Attribute Matrix. We can get the AttributeMatrix (Parent) of the input array, then the parent of the AttributeMatrix should be the input Geometry. Validate that the parent is an image geometry.

**Comment by nyoungbq** [comment]
I was unable to find a way to pass the searched image geometry path in preflight as a `filterArgs` argument, because I wanted to avoid declaring the parameter in the `parameters()` function just to ignore user input entirely
