### ISSUE TITLE
Export ASCII Data: Update the filter parameters a bit

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#544]
I think what should happen is that if the user selected "Single File" the FileSystemPath parameter should be a "Output File Path"

If the user selects the "Multiple Files" then the FileSystemPath parameter should be "output directory" type. We might need to do this with 2 separate parameters? Then link those parameters to the combo box so that the proper UI elements show up when selected. 

@jmarquisbq @nyoungbq Work together to figure out who wants to tackle this or come up with an alternate design? To me, it seems un-natural to ask for a single file then have to define the path, name and extension.

**Comment by nyoungbq** [comment]
Knowing what it looks like under the hood this should be as simple as just making the "Multiple FIles"/"Single File" parameter a linked parameter and then adding the above functionality so the other options are not shown on single file. The filepath is just assembled in the class then passed to OStreamUtilities to be written out, so just swap the assembly for the parameter value.

**Comment by nyoungbq** [comment]
I will take care of this in this PR: https://github.com/BlueQuartzSoftware/complex/pull/546
