### ISSUE TITLE
Add to ApplyTransformationToGeometry unit test to test more cases

### ISSUE THREAD

**Issue by jmarquisbq** [BlueQuartzSoftware/complex#607]
At the very least we need the matrix of tests to include Vertex geometries and Image geometries each of which should test each transformation matrix input types

**Comment by imikejackson** [comment]
@joeykleingers Did we get all of this implemented?

**Comment by joeykleingers** [comment]
> @joeykleingers Did we get all of this implemented?

This appears to be done already.
