### ISSUE TITLE
ITKOtsuMultipleThresholdsImage: Taking a lot longer to run than the original version of the filter.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/complex#627]
SIMPL-based D3D: 13 seconds.
D3D-NX: 41 seconds.

The times above were while running a Debug build and based on the following array as input to the filter:

<img width="242" alt="Screenshot 2023-06-27 at 4 54 22 PM" src="https://github.com/BlueQuartzSoftware/complex/assets/6197698/1058e25b-444c-4107-a4ac-baab72ae7484">

**Comment by imikejackson** [comment]
Release times are inline with previous versions. Closing.
