### ISSUE TITLE
DOC: Update Python Bindings Introduction Documentation

### ISSUE THREAD

**Issue by nyoungbq** [BlueQuartzSoftware/complex#728]
Specifically `Python_Introduction.rst` needs to have some more examples added to it.

This should have not only an explanation but also a python code block demonstrating how its done.

It should at least have the following added
- [x] Creating a filter
- [x] Running a filter
- [x] Running a pipeline

**Comment by imikejackson** [comment]
As of May 24. 2024 this has mostly been implemented.
