### ISSUE TITLE
Writers should create temp file, then overwrite the existing file through a file "move"

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/complex#736]
Filters that write an output file should probably be writing to a temp file next to the final output file and then using some sort of atomic filesystem "move" to rename the file to the final file name instead of streaming to the existing file.

Just truncating a file on write can have bad side effects if other applications are "watching" the file for changes. Those other applications may try to load the file while complex is still writing to the file.

std::filesystem::rename is atomic.

We will probably need a nice function to take care of this kind of thing that can be reused by all of the filters that write out files. Maybe something like a "scoped_file_renamer" class that takes 2 args, temp file name and final file name. When the object goes out of scope the rename will be performed. Any errors are reported up as filter errors/warnings. 

@JDuffeyBQ @nyoungbq Thoughts?

**Comment by nyoungbq** [comment]
#790
