### ISSUE TITLE
BUG: Executing a DREAM.3D NX pipeline with the "Write DREAM3D NX File" filter will crash if the .xdmf/.dream3d files already exists and are open in ParaView

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

I was using DREAM.3D NX to process EBSD data. Out of habit, I did not use the built-in ParaView-powered visualization of DREAM.3D NX, but rather opened the .xdmf file pointing to the .dream3d file using ParaView to visualize the data. I then changed a parameter in the pipeline to see how this affects the model. After running the pipeline _while leaving the .xdmf file opened in ParaView_, the DREAM.3D NX GUI crashed. In DREAM.3D version before NX, this was not the case, and one could update the .xdmf file with the updated .dream3d file from within ParaView.

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### What section did you encounter the error in? [Further details may be required during triage process]

GUI client

### Steps To Reproduce

This can be reproduced using the prebuilt pipelines within DREAM.3D NX. I ran the "(01) Small IN100 Archive" pipeline to generate an .h5ebsd file and then ran the "(08) Small IN100 Full Reconstruction" pipeline to generate a .dream3d and .xdmf file. One can then open the .xdmf file in ParaView and rerun the pipeline without making any changes. The GUI should then close at the filter "Write DREAM3D NX File".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyoungbq** [comment]
Hello!

Thank you for the report. This is a known issue that is Windows specific as far as we know. Unfortunately, Paraview acquires a lock on the file when you preview it, so when we attempt to modify the file/overwrite it with the updated information the system sends a terminate error signal to the application for trying to access restricted information.

We are attempting to explore workarounds at the time being, but we would need to run the application as administrator to view the status of the file for which another application holds a lock in the operating system itself, which we do not feel is an acceptable solution and would restrict usability to a portion of our userbase.

That said we will further explore the error handling to try to avoid needless crashing as well as updating the website to list this as a known issue.

For the time being, the mitigation options are as follows:
- Remove the file from the Paraview visualization before running
- Change the output file name and load that file into Paraview after running
- Utilize the integrated visualization for automatic "hot reloading"

Thanks again for the report! This is an issue we are trying to address, and I will be sure to update this thread as more improvements reduce the tedious integration with Paraview for our users. 

If necessary, you should be able to salvage the temporary `.dream3d` file that was written before the crash from a subdirectory of the parent path of the file (named an assortment of random ASCII characters). It can be dropped into the DREAM3DNX GUI to be visualized directly without the `.xdmf`.

Example temp file location:
Supplied Filepath: `C:\user\home\data\my_file.dream3d`
The temp file would be found: `C:\user\home\data\dwzDLZ7JMuV38oME4Vc5OwYZ\my_file.dream3d`

Nathan

**Comment by StopkaKris** [comment]
Hi Nathan,

Thank you for the detailed response. I wonder if a possible solution would be the way DREAM3D handles writing to other types of files that are open during pipeline execution. For example, the "Write Feature Data as CSV File" filter reports error code -15780 if the filename specified in the filter is currently open, i.e., an "Access is denied" error. Thus, the pipeline fails gracefully. Could that be implemented as a fix?

Best regards,
Krzysztof Stopka

**Comment by nyoungbq** [comment]
Hello Krzysztof,

Thank you for the suggestion. I looked into the CSVWriter and what error -15780 is checking is that the actual temp file path is writable, but it gave me an idea for an additional check that may help catch the error. I will get back to you once I have done some testing.

Nathan
