### ISSUE TITLE
BUG: HDF5 classes prematurely close on implicit copy

### ISSUE THREAD

**Issue by JDuffeyBQ** [BlueQuartzSoftware/complex#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

The HDF5 classes like `AttributeReader` are implicitly copy constructible since they don't have copy or move constructors or assignment operators. If a copy is created and then destructed, it will render that HDF5 id unusable for all other objects with that id. Therefore these classes should be move only and zero out the id on move.

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
@JDuffeyBQ @mmarineBlueQuartz  Do we have a fix for this incoming?
