### ISSUE TITLE
BUG: Prebuilt pipelines contain inconsistencies, missing files, etc, in RC-11 vs. RC-10.

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

I found inconsistencies with three prebuilt pipelines, as listed below:

1) The pipeline "Combo-EBSD-osc_r0c0" cannot be executed because the file "Combo-EBSD-120130.osc_r0c0.ang" is not provided in the "Data" directory. Also, should this pipeline has a more user friendly/readable name, to be more consistent with the other prebuilt pipelines?
2) The pipeline "AppendImageGeometryZSlice" has "Placeholder Filter" as filters 2 thru 5 in RC-11, which include just a comment block and render the pipeline unusable. In RC-10, this pipeline has the correct "Read Text Data Array" filters as filters 2 thru 5.
3) The pipeline "ApplyTransformation_Demo" is not correctly set up in RC-11. The third filter "Create Data Array" incorrectly places the Created Array into a new geometry and not into the "Group 1/Group 2" structure, and requires a few edits before the pipeline can run. This prebuilt pipeline works fine in RC-10, so perhaps there was an issue copying these pipeline settings over to RC-11.

Also, in the "Create Data Array" filter, there is a missing space in the "Filter Parameters" tab, in the phrase "Created DataArray".

Best regards,
Krzysztof Stopka

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
@StopkaKris Thank you for the report. I have addressed these issues in an upcoming PR. Some of the pipelines were not being tested by our CI bots which allowed them to fly under the radar for a bit.

**Comment by imikejackson** [comment]
https://github.com/BlueQuartzSoftware/simplnx/pull/934

**Comment by StopkaKris** [comment]
I found some additional prebuilt pipelines that appear to be missing files, or paths to files are not specified by default:

- ImportBrukerNanoEspritData, missing "Data/OrientationAnalysis/H5EspritReaderTest.h5"
- ImportEdaxOIMData, missing "Data/Hikari_Ni_Sequence.h5"
- ResampleRectGridToImageGeom, this should point to "Data/ASCIIData/RectilinearGrid.csv", based on RC-10
- ReplaceElementAttributesWithNeighbor, Filter 5 does not have proper default settings
- Import_ASCII, path to .csv file is not set in Filter 2
- FindLargestCrossSection, Filter 4 does not have proper default settings
