### ISSUE TITLE
ENH: Standardization of groups in "Filter Parameters" tab for various filters.

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#935]
### Is there an existing plan for this?

- [X] I have searched the existing discussions, release notes, and documentation.

### Description of the Feature, Filter, or Functionality?

I noticed that filters have multiple ways of asking the user for the same inputs and created objects, which would be good to try and standardize. Some examples are listed below:

Filters that require cell data:
- ```Find Feature Shapes```, ```Segment Features (Misorientation)```: "REQUIRED INPUT CELL DATA"
- ```Find Feature Reference Misorientations```, ```Find Kernel Average Misorientation```: "REQUIRED CELL DATA"
- ```Find Feature Average Orientations```: "INPUT ELEMENT DATA"
- ```Find Feature Phases```: "INPUT CELL DATA"
- ```Find Feature Phases Binary```: "REQUIRED INPUT DATA OBJECTS"

There are similar instances where Feature and Ensemble "input" vs. "required" data is specified in various filters.

Some filters ask for inputs differently:

- ```Find Feature Reference C-Axis Misalignment```: "REQUIRED CELL DATA" includes "Feature Ids", "Phases", and "Quaternions".
- ```Find Feature Reference Misorientations```: "REQUIRED CELL DATA``` includes "Cell Feature Ids", "Cell Phases", and "Quaternions".
- ```Find Feature Average Orientations```: "INPUT ELEMENT DATA" includes: "Cell Feature Ids", "Cell Phases", and "Cell Quaternions".

Other notes:
- The filter ```Find Feature Neighbor Misorientations``` lists "INPUT PARAMETER" whereas many others list "INPUT PARAMETERS".

### Version

7.0.x (DREAM3DNX beta)

### What section did you foresee your suggestion falling in? [Further details may be required during triage process]

Filter Parameters

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
@StopkaKris Here is the current list of terminology.

## Currently Used Terminology

- 1rst Group of Parameters
- 2nd Group of Parameters
- Algorithm Options
- Big Parameters
- Calculated Output Arrays
- Cell Data
- Cell Ensemble Data
- Cell Feature Data
- Conversion Parameters
- Created  Feature Data
- Created AttributeMatrix
- Created Cell Data
- Created Cell Data Objects
- Created Cell Ensemble Data
- Created Cell Feature Data
- Created Data
- Created Data Object
- Created Data Objects
- Created Data Structure Objects
- Created DataArray
- Created Element Data
- Created Element Data Object
- Created Ensemble Data
- Created Face Data
- Created Face Data Arrays
- Created Face Feature Data
- Created Face Feature Data Arrays
- Created Feature Data
- Created Geometry
- Created Image Data Objects
- Created Image Geometry
- Created Input Geometry Data Objects
- Created Objects
- Created Objects: Ensemble Data
- Created Objects/Output File Parameters
- Created Output Arrays
- Created Output Data
- Created Output Data Objects
- Created Partition Grid Data Objects
- Created Partition Grid Parameters
- Created Point Data
- Created Triangle Geometry
- Created Vertex Data
- Data Initialization
- Dynamic Column - Dynamic Row
- Dynamic Column - Fixed Row
- Element Data
- Ensemble Data
- Existing Attribute Matrix
- Face Data
- Face Ensemble Data
- Feature Data
- File List
- FileSystem Selections
- Fixed Column - Dynamic Row
- Fixed Columns - Fixed Rows
- Geometry
- Group Features Parameters
- Histogram Options
- Image Geometry Resampling/Interpolation
- Input Arrays
- Input Cell Data
- Input Cell Data Data
- Input Cell Feature Data
- Input Data
- Input Element Data
- Input Ensemble Data
- Input Feature Data
- Input Geometry
- Input Geometry and Data
- Input Geometry and Node Type Array
- Input Geometry Parameters
- Input Image Geometry
- Input Image or RectilinearGrid Geometry
- Input Parameter
- Input Parameters
- Input Vertex Data
- Input Vertex Geometry Information
- Input Vertex Mask Selection
- Linked Parameter
- Multiple Linked Parameters
- Newly Reduced Geometry
- Optional Data Mask
- Optional File Output
- Optional Parameters
- Optional Transferred Data
- Optional Variables
- Orientation Source Data
- Other Parameters
- Output Data
- Output Geometry and Data
- Output Image Geometry
- Output Image Geometry Parameters
- Output Parameters
- Output Pole Figure
- Output Set Up
- Output Vertex Geometry
- Parameters
- Renumber Features (Optional)
- Renumber Features Input Parameters
- Required Cell Data
- Required Cell Ensemble Data
- Required Cell Feature Data
- Required Data Objects
- Required Element Data
- Required Ensemble Data
- Required Face Data
- Required Face Ensemble Data
- Required Face Feature Data
- Required Feature Data
- Required Geometry
- Required Image Geometry Cell Ensemble Data
- Required Image Geometry Cell Feature Data
- Required Input Arrays
- Required Input Cell Data
- Required Input Cell Ensemble Data
- Required Input Data
- Required Input Data Objects
- Required Input DataArray
- Required Input Feature Data
- Required Objects
- Required Objects: Cell Data
- Required Objects: Cell Ensemble Data
- Required Objects: Ensemble Data
- Required Objects: Feature Data
- Required Parameters
- Required Parent Data
- Required Parent Geometry
- Required Reference Data
- Required Sampling Data
- Required Selections
- Required Triangle Geometry Face Data
- Required Triangle Geometry Face Feature Data
- Required Triangle Geometry Vertex Data
- Sampling Grid Selection
- Seeded Randomness
- Segmentation Parameters
- Smoothing Values
- Transformation Matrix Options
- Tuple Handling
- Vector Parameters
- Vertex Data

**Comment by imikejackson** [comment]
@StopkaKris Please take a look and comment on this progress.

## Newly Updated Screen Shots

![Screenshot 2024-05-01 at 14 49 43](https://github.com/BlueQuartzSoftware/simplnx/assets/5182396/c518d610-8316-4430-a73c-c2ed840d8092)


![Screenshot 2024-05-01 at 14 50 05](https://github.com/BlueQuartzSoftware/simplnx/assets/5182396/37bc1728-d51e-4d2e-a63d-ba46f1bd93dd)

**Comment by imikejackson** [comment]
@StopkaKris This is the revised list that will appear in the Separator widgets. I will need to work on the cell/feature/ensemble human labels for input parameters.

## Revised List

- Algorithm Options
- Attribute Matrix Options
- Element Data
- Geometry
- Histogram Options
- Image Geometry Resampling/Interpolation
- Input Cell Data
- Input Cell Feature Data
- Input Data
- Input Data Files
- Input Data Objects
- Input Ensemble Data
- Input Face Feature Data
- Input Feature Data
- Input Geometry
- Input Geometry Parameters
- Input Image Geometry
- Input Image or RectilinearGrid Geometry
- Input Parameter(s)
- Input Parent Data
- Input Reference Data
- Input Sampling Data
- Input Triangle Ensemble Data
- Input Triangle Face Data
- Input Triangle Geometry
- Input Triangle Geometry Face Data
- Input Triangle Geometry Face Feature Data
- Input Triangle Geometry Vertex Data
- Input Vertex Data
- Input Vertex Geometry
- Optional Data Mask
- Optional File Output
- Optional Parameters
- Optional Renumber Features
- Optional Transferred Data
- Optional Transformation Matrix Parameters
- Other Parameters
- Output Cell Attribute Matrix
- Output Cell Data
- Output Data
- Output Data Array
- Output Data Object(s)
- Output Element Data
- Output Element Data Object
- Output Ensemble Attribute Matrix
- Output Ensemble Data
- Output Face Data
- Output Face Ensemble Data
- Output Face Feature Data
- Output Feature Data
- Output File
- Output File Parameters
- Output Geometry
- Output Geometry Data Objects
- Output Geometry and Data
- Output Image Data Objects
- Output Image Geometry
- Output Output Arrays
- Output Parameters
- Output Partition Grid Data Objects
- Output Partition Grid Parameters
- Output Point Data
- Output Pole Figure
- Output Triangle Geometry
- Output Vertex Attribute Matrix
- Output Vertex Data
- Output Vertex Geometry
- Output parameters
- Random Number Seed Parameters
- Sampling Grid Selection
- Tuple Handling

**Comment by StopkaKris** [comment]
> @StopkaKris Please take a look and comment on this progress.
> 
> ## Newly Updated Screen Shots
> ![Screenshot 2024-05-01 at 14 49 43](https://private-user-images.githubusercontent.com/5182396/327206207-c518d610-8316-4430-a73c-c2ed840d8092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MDA4MjgsIm5iZiI6MTcxNDYwMDUyOCwicGF0aCI6Ii81MTgyMzk2LzMyNzIwNjIwNy1jNTE4ZDYxMC04MzE2LTQ0MzAtYTczYy1jMmVkODQwZDgwOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMjE1NTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGFiYWZhNjFiY2I1OWUxYzcyMjE4NWEyZjgwZmEyMjFjNWI4OTY0ZjdiZTMzOTEyNWU1NzExZGJkOGYzMDNkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OuJvy1KafC3rIXR8KYfOTMJN7xhBkwB9k5HaaVXLxVo)
> 
> ![Screenshot 2024-05-01 at 14 50 05](https://private-user-images.githubusercontent.com/5182396/327206284-37bc1728-d51e-4d2e-a63d-ba46f1bd93dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MDA4MjgsIm5iZiI6MTcxNDYwMDUyOCwicGF0aCI6Ii81MTgyMzk2LzMyNzIwNjI4NC0zN2JjMTcyOC1kNTFlLTRkMmUtYTYzZC1iYTQ2ZjFiZDkzZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMjE1NTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjJjODQ5NTRjNTA4NmUxYWRlOWY4YThmMmQyMjRhZDMxNTQ4OWM5ODcyNDYwZTY4ZGUyNWRhYmE5OTA1NDA0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._J5Og9hCXWy8TukLh8Rne4kx93rhFzn6b9Qt8WrWK-4)

@imikejackson This looks good!
