### ISSUE TITLE
BUG: Right-clicking on empty regions in the "Filter List" and selecting "Filter Help" crashes pipeline

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

Right-clicking on a filter under the "Favorites" and "All Filters" tab and clicking on "Filter Help" works fine, but if the right click is performed on the empty region (for example, if there are no favorited filters in the "Favorite" tab), then performing this action will cause the pipeline to crash.

Works fine:
![image](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/a6d01c2a-0e4c-46e5-9b5a-1d4ee8a74868)

Crashes:
![image](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/621353ec-a768-42c3-93bf-065d776b114d)

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmarquisbq** [comment]
@StopkaKris Thanks for bringing this to our attention. The bug has been found and fixed and will be included in the next release.
