### ISSUE TITLE
BUG: Default values in prebuilt pipelines that contain integers with commas.

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

The prebuilt pipeline “(08) Small IN100 Full Reconstruction” has “Fill Bad Data” as filter 18. The Minimum Allowed Defect Size is set to “1,000” by default and the pipeline runs fine. However, if this filter is disabled and then re enabled, an error is presented to the user. To prevent the error, the user must enter “1000” instead of “1,000”, or hit enter with the default value of "1,000", but then the error will reoccur if the filter is disabled and re enabled. Perhaps we should ensure the default numerical values do not contain commas? To be clear, the filter *does* work when entering “1,000”, it is just that the error will arise when the filter is disabled then reenabled.

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
@StopkaKris What exact version of DREAM3D-NX are you running?

**Comment by StopkaKris** [comment]
@imikejackson  This was RC-11 on Windows 10.

**Comment by imikejackson** [comment]
https://github.com/BlueQuartzSoftware/DREAM3DNX/pull/675

That is a private repo, but we were able to reproduce the issue and get a fix implemented

**Comment by imikejackson** [comment]
Merged. Closing.
