### ISSUE TITLE
BUG: Some filters contain a space in default attribute arrays

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

Some filters by default specify “Cell Data”, but the requirement for other filters is “CellData”, so this requires either renaming the original filter placed at the start of prebuilt pipelines (if they are being modified), or changing the inputs for all subsequent filters in a prebuilt pipeline.

Possible solution: remove space in “Cell Data” for filters “Read Oxford Instr. EBSD Data (.ctf)”, “Read Oxford Aztec Data (.h5oina)”, “Read EDAX EBSD Data (.ang)”, etc. Similar instances appear in filter “Find Feature Centroids” which requires “Data Container/Feature Data” for the Cell Feature Attribute Matrix, whereas the Cell Feature Ids is, by default, “CellData/FeatureIds”. Also, filter “Find Feature Neighbors” is already formatted properly. Thus,it would be good to make these consistent and remove any spaces present by default in filters.

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
This was an inconsistency that got started somewhere in the rewrite but never straightened out. We are currently working on getting this consistency back into DREAM3D-NX.

**Comment by imikejackson** [comment]
https://github.com/BlueQuartzSoftware/simplnx/pull/972
