### ISSUE TITLE
DOC: Misspelled words, request to wrap messages in "Filter Parameters" tab, etc.

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Documentation Issue or Improvement

Please see the request/suggestions below to fix documentation and messages to DREAM.3D users:

1. The documentation for the ```Compute Average C-Axis Orientations``` filter has “then” misspelled as “thne”.
2. The filters for which warning messages were added in the Filter Parameters tab should be modified as follows:
2a. Create a link break between "Feature Data Modification Warning" and the actual warning to improve readability.
2b. Can we wrap the text of the actual warning message? Without wrapping it, the Filter Parameters tab requires the user to scroll to the right to see the parameters as shown in the screenshot below.
2c These filters are also the only ones that state "The values below are in the US locale". Is this essential for these filters, or could it be assumed/written somewhere that everything DREAM.3D reports is in the US locale?

![image](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/780a72d3-c7df-4568-8092-21823d6c4caf)

### Version

DREAM3D NX (version 7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
@StopkaKris Here are all the changes. Thoughts? 

![Screenshot 2024-07-08 at 15 06 03](https://github.com/BlueQuartzSoftware/simplnx/assets/5182396/612498f1-2874-44df-a092-bc25032d6068)

**Comment by StopkaKris** [comment]
@imikejackson that looks great regarding the first two points. What are your thoughts on removing "The values below are in the US locale"?

**Comment by imikejackson** [comment]
@StopkaKris We wanted to be clear about the formatting of numbers that appear in these messages which is why we have the blanket statement. Right now we don't have a way for the filter to turn that message off. The feedback from our European users was that there was some confusion when numbers were presented in different locales so we try to make it clear how numeric values are formatted.

**Comment by StopkaKris** [comment]
@imikejackson That makes sense, thank you for clarifying.

**Comment by imikejackson** [comment]
@StopkaKris I'm going to close this issue as everything is either addressed or has been committed to the repos and will be in the next version of DREAM3D-NX.
